# Generated by Django 2.1.2 on 2018-10-21 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.RenameField(
            model_name='habitacion',
            old_name='capacidad',
            new_name='numero',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='precio',
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscador.TipoHabitacion'),
        ),
    ]
