# Generated by Django 2.1.2 on 2018-10-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0002_auto_20181020_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='anio_expira',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='reserva',
            name='comentarios',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='reserva',
            name='localizador',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='reserva',
            name='mes_expira',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='reserva',
            name='nombres_tarjeta',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AddField(
            model_name='reserva',
            name='numero_ccv',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tarjeta_credito',
            field=models.IntegerField(default=None),
        ),
    ]
