# Generated by Django 2.1.2 on 2018-10-27 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0004_auto_20181021_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='anio_expira',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='comentarios',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='localizador',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='mes_expira',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nombres_tarjeta',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='numero_ccv',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tarjeta_credito',
            field=models.IntegerField(),
        ),
    ]
