# Generated by Django 2.1.2 on 2018-10-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0006_auto_20181028_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='tipo_tarjeta',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
