# Generated by Django 2.1.2 on 2018-10-29 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0007_reserva_tipo_tarjeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='habitacion',
            options={'verbose_name_plural': 'Habitaciones'},
        ),
        migrations.AlterModelOptions(
            name='tipohabitacion',
            options={'verbose_name_plural': 'Tipo de habitaciones'},
        ),
    ]
