# Generated by Django 2.1.2 on 2018-10-29 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0008_auto_20181029_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='precio_noche',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
            preserve_default=False,
        ),
    ]
