# Generated by Django 2.1.2 on 2018-10-29 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0009_reserva_precio_noche'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarjetacredito',
            options={'verbose_name_plural': 'Tarjetas de crédito'},
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tarjeta_credito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscador.TarjetaCredito'),
        ),
    ]
