# Generated by Django 2.1.2 on 2018-10-29 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0010_auto_20181029_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='tarjeta_credito',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='tipo_tarjeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buscador.TarjetaCredito'),
        ),
    ]
